plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()

    maven { url "https://maven.fabricmc.net" }
    maven { url "https://jitpack.io" }

    maven { url "https://maven.wispforest.io" }
    maven { url "https://maven.isxander.dev/releases" }
    maven { url "https://maven.shedaniel.me" }
    maven { url "https://maven.terraformersmc.com/releases" }
    maven { url "https://maven.ladysnake.org/releases" }

    maven { url "https://theo.is-a.dev/maven/" }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

loom {
    splitEnvironmentSourceSets()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    implementation include("net.objecthunter:exp4j:0.4.8")
    implementation "com.google.code.gson:gson:2.8.9"

    modImplementation "dev.isxander:yet-another-config-lib:${project.yacl_version}"
    modImplementation "com.terraformersmc:modmenu:${project.modmenu_version}"

    modImplementation "io.wispforest:owo-lib:0.11.2+1.20.1"

    modImplementation "maven.modrinth:ait:${project.ait_version}"

    modImplementation("com.github.amblelabs:amblekit:${project.amblekit_version}") {
        transitive = true
    }
}